version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
    command: ["sh", "-c", "php -S 0.0.0.0:80 -t public & php server.php"]